#' Example table of sample names and conditions
#'
#' Example condition table with two columns. Column 1 contains sample name,
#' column 2 contains condition name. Use in conjuncture with count_table
#'
#' @name condition_table
#'
NULL


#' Example count table of GTEx RNA-seq experiment
#'
#' Count table generated using data downloaded from Recount2 website
#' that processed Raw GTEx dataset.
#'
#' @name count_table
#' @references \url{https://jhubiostatistics.shinyapps.io/recount/}
NULL


#' Example count table of GTEx RNA-seq experiment, fitered by count_filter function
#'
#' Count table is filtered version of example count_table. Contain 16766 genes that
#' pass the filter.
#'
#' @name count_table.filtered
#' @references \url{https://jhubiostatistics.shinyapps.io/recount/}
NULL


#' Example list of combinations generated by comb_gen function.
#'
#' @name combinations
#'
#'
NULL

