#' @title Plot percent increase in detection of DE genes across replicate levels
#'
#' @description
#' \code{ggplot2_marginPlot} function plots the percent increase in number of DE
#' genes identified at each step-wise increase in replicate level.
#'
#' @details
#' The percent increase is calculated as (margin*100%)/(num. of DE genes at the
#' lower replicate level). The results are visualized as bar plots. Either mean
#' or median can be used for the calculation.
#'
#' @param deg The list of DE genes generated by one of ERSSA::DE_*.R scripts.
#' @param stat The statistic used for plotting. Options include "Mean", "Median".
#' Default='mean'.
#' @param path Path to which the plot will be saved. Default to current working
#' directory.
#'
#' @return A list is returned containing:
#'  \itemize{
#'   \item{gg_object} {the ggplot2 object, which can then be further
#'   customized.}
#'   \item{marg_diff.dataframe} {the tidy table version of percent changes for
#'   plotting.}
#' }
#' @author Zixuan Shao, \email{Zixuanshao.zach@@gmail.com}
#'
#' @examples
#' #load edgeR deg object generated by erssa_edger using example dataset
#' #only 5000 genes and 4 replicates tested to speed up runtime
#' data(deg.partial, package = "ERSSA")
#'
#' gg_margin = ggplot2_marginPlot(deg.partial)
#'
#' @export


ggplot2_marginPlot = function(deg=NULL, stat='Mean', path='.'){

  if (is.null(deg)){
    stop('Missing required deg argument in ggplot2_marginPlot function')
  }

  #calculate stat.
  name = c()
  percent_diff = c()

  for (index in seq(1, length(deg)-1)){
    num_i = sapply(deg[[names(deg)[index]]], function(x) length(x))
    num_j = sapply(deg[[names(deg)[index+1]]], function(x) length(x))
    if (stat=='Mean'){
      per_diff = (mean(num_j)-mean(num_i))*100/mean(num_i)
    } else if (stat=='Median'){
      per_diff = (stats::median(num_j)-stats::median(num_i))*100/
        stats::median(num_i)
    } else {
      stop('Only mean or median currently supported for plotting marginal
           difference in Num. of DE genes.')
    }
    percent_diff = c(percent_diff, per_diff)

    if (index != length(deg)-1){
      name = c(name, paste0(names(deg)[index], ' \u2192 ', names(deg)[index+1]))
    } else {
      name = c(name, paste0(names(deg)[index], ' \u2192 ', names(deg)[index+1]))
    }
  }

  #round the diff
  rounded_per_diff = sapply(round(percent_diff,1), function(x) paste0(x,'%'))

  #dataframe for plotting
  per_diff_df = data.frame(replicate=name, per_diff=percent_diff,
                           rounded_per_diff=rounded_per_diff)
  per_diff_df$replicate = factor(per_diff_df$replicate, levels =
                                   per_diff_df$replicate)

  #plot
  gg = ggplot2::ggplot(per_diff_df, ggplot2::aes(replicate, per_diff)) +
    ggplot2::geom_col(width=0.7) +
    ggplot2::theme_bw() +
    ggplot2::labs(x='', y=paste0('Percent difference in ',tolower(stat),
                                 ' of number of DE genes (%)')) +
    ggplot2::geom_text(ggplot2::aes(label = rounded_per_diff), vjust =
                         ifelse(per_diff_df$per_diff >= 0, -0.2, 1.2)) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

  #create dir to save results
  folder_path = file.path(path)
  dir.create(folder_path, showWarnings = FALSE)


  #save plot and return ggplot2 object for additional customarization if needed
  ggplot2::ggsave(filename=file.path(path,'ERSSA_plot_MarginalDiff.png'),
         plot=gg, dpi=300, width = 20,
         height = 15, units = "cm")

  return(list(gg_object=gg, marg_diff.dataframe = per_diff_df))
}


