#' @title Plot number of DE genes
#'
#' @description
#' \code{ggplot2_dotplot} function plots the number of differentially expressed
#' (DE) genes in each test.
#'
#' @details
#' The number of DE genes are plotted as dots grouped by the associated
#' replicate level. At each replicate level, a boxplot is drawn to mainly show
#' the first and third quartiles as well as the median. Additionally,
#' A red line is drawn representing the mean at each replicate level. A
#' horizontal dashed blue line represents the number of DE genes found with
#' all samples.
#'
#' @param deg The list of DE genes generated by one of ERSSA::DE_*.R scripts.
#' @param path Path to which the plot will be saved. Default to current working
#' directory.
#'
#' @return A list is returned containing:
#'  \itemize{
#'   \item{gg_object} {the ggplot2 object, which can then be further
#'   customized.}
#'   \item{deg_dataframe} {the tidy table version of DEG numbers for plotting.}
#'   \item{full_num_DEG} {The number of DE genes with all samples included.}
#' }
#' @author Zixuan Shao, \email{Zixuanshao.zach@@gmail.com}
#'
#' @examples
#' #load edgeR deg object generated by erssa_edger using example dataset
#' #test dataset with 1000 genes, 4 replicates and 20 comb. per rep. level
#' data(deg.partial, package = "ERSSA")
#'
#' gg_dot = ggplot2_dotplot(deg.partial)
#'
#' @export


ggplot2_dotplot = function(deg=NULL, path='.'){

  if (is.null(deg)){
    stop('Missing required deg argument in ggplot2_dotplot function')
  }

  #convert input list of DEG into tidy format
  #Loop through all replicate levels except full replicate level
  num_DEG = c()
  rep_level = c()
  comb_ID = c()

  for (rep_i in names(deg)[names(deg) != 'full']){

    deg_rep_i = deg[rep_i][[1]]
    rep_level = c(rep_level, rep(strsplit(rep_i,split='_')[[1]][2],
                                 length(names(deg_rep_i))))

    for (comb_i in names(deg_rep_i)){

      deg_comb_i = deg_rep_i[comb_i][[1]]
      num_DEG = c(num_DEG, length(deg_comb_i))
      comb_ID = c(comb_ID, strsplit(comb_i, split='_')[[1]][2])

    }

  }

  full_num_DEG = length(deg$full$comb_1)

  #create data frame for plotting
  deg_df = data.frame(num_DEG = num_DEG, rep_level = rep_level, comb_ID = comb_ID)
  deg_df$rep_level = factor(deg_df$rep_level, levels = unique(deg_df$rep_level))

  #plot DE genes at each replicate level
  gg = ggplot2::ggplot(deg_df, ggplot2::aes(rep_level, num_DEG)) +
    ggplot2::geom_boxplot() +
    ggplot2::geom_dotplot(binaxis='y', stackdir='center',dotsize=1.5,
                          binwidth = max(deg_df$num_DEG)/150) +
    ggplot2::theme_bw() +
    ggplot2::geom_hline(ggplot2::aes(yintercept=full_num_DEG,
                                     color = "Full dataset"), size=0.75,
                        linetype="dashed", show.legend = TRUE) +
    ggplot2::stat_summary(ggplot2::aes(rep_level, num_DEG, colour="Mean"),
                          group=1, fun.y='mean', geom='line', size=1) +
    ggplot2::scale_colour_manual(values=c("Mean"="red", "Full dataset"="blue"))+
    ggplot2::labs(x='Replicate number', y='Number of DE genes', colour="") +
    ggplot2::guides(color = ggplot2::guide_legend(
      override.aes = list(linetype = c("dashed", "solid"))))

  #create dir to save results
  folder_path = file.path(path)
  dir.create(folder_path, showWarnings = FALSE)


  #save plot and return ggplot2 object for additional customarization if needed
  ggplot2::ggsave(filename=file.path(path,'ERSSA_plot_NumOfDEGenes.png'),
         plot=gg, dpi=300, width = 20,
         height = 15, units = "cm")

  return(list(gg_object=gg, deg_dataframe = deg_df,
              full_num_DEG = full_num_DEG))
}


